### ISSUE TITLE
Error in installing sass while deploying materials cloud frontend

### ISSUE THREAD

**Issue by waychal** [materialscloud-org/issues#12]
In Materials Cloud, ruby sass is used to compile sass files into css files. Ruby sass was the original implementation of sass, but it reached its end of life in March 2019 and is no longer supported [1].

So it throws below error while installing grunt-sass:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Remove ruby sass dependency and instead install it from dart sass.

[1] https://sass-lang.com/ruby-sass

**Comment by waychal** [comment]
Fixed the issue on mac.

Changes:
1. If sass is previously installed on your machine, uninstall it using command: sudo gem uninstall sass
2. As we are now using dart sass, check if it is required to install dart on your machine [1]
3. Updated Gruntfile and package.json 

Currently changes are available only in develop branch in frontend-discover (commit: 5f32184) and frontend-explore (commit: 8135e8a) repositories. 
 
[1] https://dart.dev/get-dart

**Comment by waychal** [comment]
Below steps are not required anymore in installation.

```
sudo gem install sass bundler
bundle install
```

**Comment by ltalirz** [comment]
this should be fixed now, correct @waychal ?
if yes, feel free to close this issue

**Comment by waychal** [comment]
@ltalirz Its difficult to say. This issue is random. Right now it is fixed and we are not getting it on any server.
