### ISSUE TITLE
explore link for phonon plot in 2dtopo is not working

### ISSUE THREAD

**Issue by waychal** [materialscloud-org/issues#14]
Going to
https://www.materialscloud.org/discover/2dtopo/details/IrNbTe4

And clicking on the AIiDA icon for the phonon dispersion, it’s empty:
https://www.materialscloud.org/explore/2dtopo/details/6d03714f-fb1d-46a2-8b32-be3458592e44?nodeType=DATA

Also for other phonons

**Comment by ltalirz** [comment]
tested just now; seems to be fixed.
