### ISSUE TITLE
Standalone [EXPLORE section], to be hosted at the own server

### ISSUE THREAD

**Issue by blokhin** [materialscloud-org/issues#16]
We're basically speaking about the AiiDA web-GUI, which is now Materials.Cloud.

Please, share, if there are any plans to open-source it.

**Comment by ltalirz** [comment]
Done today! https://github.com/materialscloud-org/aiida-explorer

There is also an older repo that was used to create a docker container for this JS app
https://github.com/materialscloud-org/aiida-explorer-container

(probably needs to be updated)
