### ISSUE TITLE
Left side menu in Explore grid view for 3DCD and curated-cofs

### ISSUE THREAD

**Issue by waychal** [materialscloud-org/issues#17]
In explore grid view, style for left menu is not displayed correctly for 3DCD and curated-cofs sections.

see attached image.

![Schermata del 2020-06-16 11-26-06](https://user-images.githubusercontent.com/25031092/84900439-68f46f00-b0aa-11ea-9663-f4860323a35d.png)

**Comment by ltalirz** [comment]
Fixed now on dev-www
https://dev-www.materialscloud.org/explore/curated-cofs/grid/calculations

![image](https://user-images.githubusercontent.com/1053245/94787348-7f60d500-03d2-11eb-9409-18046fc28878.png)
