### ISSUE TITLE
Introductory "splash screen" on home page might be confusing

### ISSUE THREAD

**Issue by borellim** [materialscloud-org/issues#20]
Feedback from an Archive user:
>Entering the website from materialscloud.org and clicking on archive, I see attached picture 1. It was hard for me at first to find that I should again click on archive on top to move to the page that I can upload my entry

Indeed, the first thing one sees is "About / Overview / News / Statistics / Partners".

Picture recreated here: 
![Schermata del 2020-06-26 13-27-01](https://user-images.githubusercontent.com/6683587/85852545-181efd80-b7b1-11ea-9ef3-e04c4beec776.png)

**Comment by ltalirz** [comment]
Just an additional clarification:
"Clicking on the archive" refers to clicking on the archive section in the materials cloud banner:
![image](https://user-images.githubusercontent.com/1053245/85856742-d003d900-b7b8-11ea-9199-5c67d475ed00.png)

Nicola at some point suggested to make the sections clickable & link directly to the respective section pages - I originally was against it since it means adding links inside svg and I wasn't sure how well this was supported by different browsers (+ I tried and was unable to make it work).

On second thought, however, I have heard the same thing from other Materials Cloud users and I think we should try to implement this - even if it means splitting up the image into multiple ones.

mentioning @giovannipizzi for comment

**Comment by ltalirz** [comment]
P.S. "Not able to make it work": I think I was able to add the links and make it work when just loading the svg image from disk, but not when putting it into the AngularJS application

**Comment by borellim** [comment]
Ah. I seem to have misunderstood the user's comment. I'll rephrase the title, then.

As for your point: I think this black "splash screen" is very pretty ... but quite useless. We effectively have a double home page.
At least your suggestion would make it functional, but I would be in favor of removing it entirely. Or maybe integrating it into the real home page (not sure how).

**Comment by ltalirz** [comment]
> As for your point: I think this black "splash screen" is very pretty ... but quite useless. We effectively have a double home page.
At least your suggestion would make it functional, but I would be in favor of removing it entirely. Or maybe integrating it into the real home page (not sure how).

Hehe, you have my support but I suggest you talk to Nicola about this ;-)

**Comment by giovannipizzi** [comment]
I in general agree that we might want to try to remove this page... Anyway, also Marco Gibertini reported the issue that he would expect to jump directly to the section. Pinging @vgranata and @waychal who were in CC

@ltalirz what did you use exactly?

Did you try this?
https://www.w3schools.com/tags/tag_area.asp

There are even online generators, e.g. this https://www.image-map.net (I didn’t try it out but in case I imagine there are also others)

**Comment by ltalirz** [comment]
@giovannipizzi I tried SVG links
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a

**Comment by waychal** [comment]
I also vote for removing banner if possible. It is not really useful from user point of view. If we want to keep it then either add direct links to the sections or display it on top on the home page. 

I didn't get time to check svg and add links after Marco's email.

**Comment by chrisjsewell** [comment]
lol I come to say the same the same thing; to be a bit harsh, its literally the most useless thing I've seen in any web design, given that (a) it gives you absolutely no clue as to what materials cloud actually is, (b) all it allows you to do is click through to the actual homepage.
I can't believe this is still a thing after nearly a year, just redirect straight to the actual homepage

**Comment by eimrek** [comment]
Closing this as the splash screen has been removed.
