### ISSUE TITLE
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by princedft** [materialscloud-org/issues#22]
Sir,
I am trying to use SEEK-Path K finder. But, it is showing "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application" from the last four days continuously. Will you please help to solve this.

**Comment by ltalirz** [comment]
Hi @princedft , for me the tool is working fine https://www.materialscloud.org/work/tools/seekpath

Would you mind providing some more details?

@asle85 Just checking: are you receiving notifications for new issues on this repository?

**Comment by elsapassaro** [comment]
No, I didn't receive any notifications for seekpath.

**Comment by ltalirz** [comment]
@asle85 I meant this repository, i.e. materialscloud-org/issues
Simply make sure you're watching it 

![image](https://user-images.githubusercontent.com/1053245/94787076-18432080-03d2-11eb-9b85-d58b684bb18c.png)

**Comment by elsapassaro** [comment]
Sorry, I misunderstood, now I'm watching it

**Comment by princedft** [comment]
![Untitled](https://user-images.githubusercontent.com/69404678/94791834-cc09d780-03f5-11eb-9d25-4dafe421c775.png)

**Comment by princedft** [comment]
Sir,
This is the issue. I am uploading my CIF file and it is showing this error message. 
It is working fine earlier. But, from last week, This kind of error is occurring. 
Will you please resolve this. 
With regards

**Comment by ltalirz** [comment]
Hi @princedft , thanks for the report - can you please attach the CIF file to your comment?
You may need to rename the extension to txt

**Comment by princedft** [comment]
Please find the attachment
[NiTe2.txt](https://github.com/materialscloud-org/issues/files/5311330/NiTe2.txt)
.

**Comment by giovannipizzi** [comment]
Hi, thanks for the file, very useful.
You have some non-UTF-8 characters in your file for some reason: at least in _chemical_name_common (there is some semi-hidden character between the starting quote `'` and `Te`). If you remove them, your file will work.
I've anyway opened materialscloud-org/tools-seekpath#10 to print a more friendly error message, and I will fix this in the future. I'm going to close this issue.
