### ISSUE TITLE
SeeK-path cannot read vasp file

### ISSUE THREAD

**Issue by PaganiniBJ** [materialscloud-org/issues#26]
Hello! 
The SeeK-path tool cannot read my POSCAR file sent from my MacBook. It doesn't even read the vasp official file. This problem did not exist last week. Can someone help me?
I appreciate that
[POSCAR.txt](https://github.com/materialscloud-org/issues/files/7600931/POSCAR.txt)
.

**Comment by PaganiniBJ** [comment]
However, the file works on Windows.

**Comment by ltalirz** [comment]
Thanks for the report @PaganiniBJ - I'm not aware of any difference between uploading files on Windows & Mac.
I suggest you try reproducing the issue, and if it persists, reporting exactly what happens.

@giovannipizzi Someone from the Materials CLoud team will probably need to start adding themselves to the watchers of this repository
![image](https://user-images.githubusercontent.com/1053245/143409651-3288bf7a-9ea9-4391-9d02-29335b6e4811.png)

**Comment by PaganiniBJ** [comment]
@ltalirz Thank you for the fast response. The issue persists.
The attached picture is the warning I get after I upload the file. The same warning occurs in either 4G or Wifi environment.
<img width="1440" alt="Screenshot 2021-11-25 at 5 27 06 PM" src="https://user-images.githubusercontent.com/95016194/143415874-43bddb27-fd82-49b9-a7be-ed7de5c04f4c.png">

**Comment by ltalirz** [comment]
Could you please attach the file you are uploading as well?

**Comment by PaganiniBJ** [comment]
@ltalirz Sure. The uploaded file is just in my first post here; I'm not sure if you can see. nvm, I can upload once more.
[POSCAR.txt](https://github.com/materialscloud-org/issues/files/7602081/POSCAR.txt)

**Comment by ltalirz** [comment]
Hi @PaganiniBJ , sorry I overlooked it in your first post.
I've reproduced that the file doesn't work with seekpath; let's wait for the people developing the seekpath tool to get back to you.

When you wrote "the file works with Windows", did you mean "upload the file to seekpath under windows" or "run the file using Vasp in Windows"?

**Comment by PaganiniBJ** [comment]
@ltalirz I meant "upload the file to seekpath under windows", and then it works well

**Comment by ltalirz** [comment]
> @ltalirz I meant "upload the file to seekpath under windows", and then it works well

I tried that (downloading your file under Windows & uploading it to the tool) and it did not work either.

To me that suggests some difference between the files you are uploading under windows & the other OS (line endings? I don't know ...).

**Comment by PaganiniBJ** [comment]
@ltalirz There should be no difference. I asked someone else did for me on a very old PC. Therefore, I can only guess this might be a compatibility issue with newer computer?

**Comment by PaganiniBJ** [comment]
@ltalirz Hello!! One more thing I wish to mention is that although it works on PC environment, I just realised the result was not correct. This seems not for a diamond structure.
![1](https://user-images.githubusercontent.com/95016194/143520690-4f596889-302a-4fc0-8135-6ec7ba7b6a87.png)
![2](https://user-images.githubusercontent.com/95016194/143520705-11e34599-0733-4efd-9175-1dd3acb3535d.png)

**Comment by giovannipizzi** [comment]
Hi - I'm not sure of your errors but it must be an issue on your side when uploading the files.

1. the file you uploaded misses the line with the chemical element names. So I think the file is wrong (if you e.g. add a line with "Ge" above the line with "2", it works)
2. The screenshot must come from a different file (it has 4 atoms, Cu Ag O O, so it cannot come from the file you uploaded).

I'm closing as I don't think it's a bug in the code. If you think it's a bug in the code instead, please reopen.
