### ISSUE TITLE
SeeK-path: Appearence of U+00a0 characters when copy-pasting coordinates in Firefox

### ISSUE THREAD

**Issue by jekuszynski** [materialscloud-org/issues#28]
When attempting to copy and paste from Firefox browser, copy and pasted coordinates from SEEK results in a series of U+00a0 characters replacing the spaces in code. 

![SeeKError](https://user-images.githubusercontent.com/66791402/210288151-e2187b15-01aa-4068-9cd6-526d95c28e7e.png)

These characters then result in code being unable to run in QE until they are replaced with whitespaces/tabs. Error is **not** reproduced in clean install of Edge or Chrome. 

Is this something that could be fixed for this browser?

**Comment by eimrek** [comment]
Dear @jekuszynski, sorry that this issue was unaddressed for so long.

I'm closing the issue as i'm not able reproduce this problem. 

Please try with up-to-date version of firefox and if the issue persists, feel free to elaborate and re-open the issue.
