### ISSUE TITLE
Link SynthesisConditionFinder

### ISSUE THREAD

**Issue by Gelaendesau** [materialscloud-org/issues#29]
Hi, 
since a couple of month the link to the SyCoFinder on the website is no longer working. When using the direkt link https://www.materialscloud.org/work/tools/sycofinder it is still accessible, but when going by materialsclod.org --> work --> tools, it is only visible but no longer selectable. 
Would be great, if you could fix this, since many people in our institute are working with this tool.
Best, L. P.

**Comment by eimrek** [comment]
Dear @Gelaendesau, thanks a lot for bringing this to our attention. It's a pity that somehow these issues were overlooked and this simple problem persisted so long. Now it's fixed.

**Comment by Gelaendesau** [comment]
Hi,

thank you so much! That’s now much more comfortable.

All the best,
Lena

Von: Kristjan Eimre ***@***.***>
Gesendet: Dienstag, 10. Oktober 2023 21:28
An: materialscloud-org/issues ***@***.***>
Cc: Pilz, Lena (IFG) ***@***.***>; Mention ***@***.***>
Betreff: Re: [materialscloud-org/issues] Link SynthesisConditionFinder (Issue #29)


Dear @Gelaendesau<https://github.com/Gelaendesau>, thanks a lot for bringing this to our attention. It's a pity that somehow these issues were overlooked and this simple problem persisted so long. Now it's fixed.
