### ISSUE TITLE
expose AiiDA REST API in docker container?

### ISSUE THREAD

**Issue by ltalirz** [materialscloud-org/issues#6]
In order for people to be able to prepare their data for the materials cloud discover/explore sections inside jupyter, it would be great if they could explore their AiiDA database using the Materials Cloud EXPLORE JS app.

People can already run the REST API inside the docker container and connect to it from a jupyter notebook (I've just added a notebook for this to mc-aiida).

However, this does not allow one to hook up the REST API to the Materials Cloud EXPLORE backend, since the REST API is running on 127.0.0.1 of the docker container, while the browser runs on  another machine.

I wonder - in order to make this work, is it necessary to expose the AiiDA REST API of the docker container to the world?
Or can one somehow "forward" the 127.0.0.1 of the docker container through jupyter to the EXPLORE JS app?

Independent of this, we should decide whether we want to be able to expose the REST API or not (which may have other use cases besides this).

Mentioning @oschuett , @giovannipizzi for comments

**Comment by oschuett** [comment]
I think the simplest solution would be to write a  jupyter server extension that forwards all requests below eg. `jupyter_base_url + "/aiida_api/"` to the local AiiDA service. For inspiration have a look [here](https://github.com/oschuett/appmode/blob/master/appmode/server_extension.py#L100).

**Comment by ltalirz** [comment]
Has long been implemented, e.g. via `ngrok`
