### ISSUE TITLE
Double click to toggle event is not working for specific kpoints node in 2D

### ISSUE THREAD

**Issue by waychal** [materialscloud-org/issues#9]
Double click toggle event is not working for this specific kpoints node in 2D structure: https://www.materialscloud.org/explore/2dstructures/details/41495fe0-6d10-4d55-8d49-b284c0a52de5?nodeType=NODE

This event works fine for other kpoints visualizer.

**Comment by waychal** [comment]
For this specific kpoint, 
```
# file: BZVisualizer.js from seekpath
canvas3d.addEventListener('dblclick', bz_switch_enable);
```
is fired twice and not once as it works in other cases. In first call `bz_switch_enable` enables the div and in second call it disables it. So its looks like no action is taken.

**Note**: find if there are any other cases like this.

**Comment by waychal** [comment]
It is decided to remove div + double click event to toggle interaction and add button on top for it to toggle the interaction.
It will also solve the problem of enabling this functionality on iphone and ipad.

**Comment by ltalirz** [comment]
seems to be working fine now
https://www.materialscloud.org/explore/2dstructures/details/41495fe0-6d10-4d55-8d49-b284c0a52de5?nodeType=NODE
